config/routes.rb
Rails.application.routes.draw do
  resources :workouts
  root 'home#index'
  get 'dashboard' => 'home#dashboard'
  
  get '/logout' => 'auth0#logout'
  post 'auth/auth0', as: 'authentication'        # Triggers authentication process
  get 'auth/auth0/callback' => 'auth0#callback' # Authentication successful
  get 'auth/failure' => 'auth0#failure'         # Authentication fail
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/workout.rb
class Workout < ApplicationRecord
  include PgSearch
  
  pg_search_scope :filtered_search,
    against: [:title, :description],
    using: [:tsearch, :trigram]
  
  has_rich_text :description
  has_one_attached :video_clip
  
  validates :video_clip, presence: true
  validates :title, length: { in: 2..25 }
  validates :description, length: { minimum: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include HomeHelper
  include Pundit
  protect_from_forgery
end

app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  def callback
    session[:userinfo] = request.env['omniauth.auth']
    redirect_to '/dashboard'
  end
  
  def failure
    error_msg = request.env['omniauth.error']
    error_type = request.env['omniauth.error.type']

    # It's up to you what you want to do with the error information
    # You could display it to the user or log it somehow.
    Rails.logger.debug("Auth0 Error: #{error_msg}. Error Type: #{error_type}")

    render :failure
  end
  
  def logout
    reset_session
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]
  
  def index
  end

  def dashboard
    authorize self
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  include Pagy::Backend

  # GET /workouts
  # GET /workouts.json
  def index
    search_param = params[:search]
    
    if search_param.present?
      @paginated_results, @workouts = pagy(Workout.filtered_search(search_param))
    else
      @paginated_results, @workouts = pagy(Workout.all)
    end
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workout_params
      params.require(:workout).permit(:title, :description, :video_clip, :search, video_thumbnails: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def user_signed_in?
    session['userinfo'].present?
  end

  def authenticate_user!
    if user_signed_in?
      @current_user = session['userinfo']
    else
      redirect_to root_path
    end
  end
  
  def current_user
    @current_user
  end

  def reset_session
    session['userinfo'] = nil if session['userinfo'].present?
  end
end

app/helpers/view_helper.rb
module ViewHelper
  include Pagy::Frontend
  
  def greeting
    if current_user.present?
      @greeting = "Welcome, #{current_user['info']['name'].split.first}!"
      @link = dashboard_path
    else
      @greeting = 'Open Wellness'
      @link = root_path
    end
  end

  def login_or_out
    if current_user.present?
      link_to('Log Out', logout_path, class: 'nav-link')
    else
      link_to('Log In', authentication_path, method: :post, class: 'nav-link')
    end
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/auth0/failure.html.erb
<center>
  <h1>Sorry, something broke. Please try again later.</h1>
</center>

app/views/home/dashboard.html.erb
<h1>Home#dashboard</h1>
<p>Find me in app/views/home/dashboard.html.erb</p>

app/views/home/index.html.erb
<div class="container">
  <center>
    <img src="https://cdn.auth0.com/styleguide/1.0.0/img/badge.svg">
    
    <h1>Open Wellness</h1>

    <%= button_to 'Login', 'auth/auth0', method: :post %>
  </center>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>Open Wellness</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          Open Wellness
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item">
            Story
          </a>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              Programmes
            </a>

            <div class="navbar-dropdown">
              <a class="navbar-item">
                About
              </a>
              <a class="navbar-item">
                Jobs
              </a>
              <a class="navbar-item">
                Contact
              </a>
              <hr class="navbar-divider">
              <a class="navbar-item">
                Report an issue
              </a>
            </div>
          </div>
          
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              Workouts
            </a>

            <div class="navbar-dropdown">
              <a class="navbar-item">
                About
              </a>
              <a class="navbar-item">
                Jobs
              </a>
              <a class="navbar-item">
                Contact
              </a>
              <hr class="navbar-divider">
              <a class="navbar-item">
                Report an issue
              </a>
            </div>
          </div>
          
          <a class="navbar-item">
            Contact
          </a>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
<!--
              <a class="button is-primary">
                <strong>Sign up</strong>
              </a>
-->
              <span class="button is-light"><%= login_or_out %></span>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <section class="section">
      <div class="container">
        <%= yield %>
      </div>
    </section>
    <footer class="footer">
      <div class="content has-text-centered">
        <p>
          <strong>Open Wellness</strong> by <a href="https://derekcrosson.co.za" target="_blank" title="Derek Crosson's personal blog">Derek Crosson</a>. Use this to build a cool SaaS product.
        </p>
      </div>
    </footer>
  </body>
</html>

app/views/workouts/_form.html.erb
<%= form_with(model: workout, local: true) do |form| %>
  <% if workout.errors.any? %>
    <div class="notification is-danger">
      <button class="delete"></button>
      <h2><%= pluralize(workout.errors.count, "error") %> prohibited this workout from being saved:</h2>
      <ul>
        <% workout.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="columns">
    <div class="column is-half">
      <div class="field">
        <%= form.label :title, class: "label" %>
        <div class="control">
          <%= form.text_field :title, class: "input is-dark is-radiusless", placeholder: "e.g. 10 minute HIIT Home Workout" %>
        </div>
      </div>
      
      <div class="field">
        <%= form.label :description, class: "label" %>
        <%= form.rich_text_area :description, style: "height: 350px;" %>
      </div>
    </div>
    <div class="column">
      <div class="field">
        <%= form.label :video_clip, class: "label" %>
        <div class="file has-name is-dark is-fullwidth">
          <label class="file-label is-fullwidth">
            <%= form.file_field :video_clip, class: "file-input", style: "display: none;" %>
            <span class="file-cta">
              <span class="file-icon">
                <i class="fas fa-upload"></i>
              </span>
              <span class="file-label">
                Choose a file...
              </span>
            </span>
            <span class="file-name">
              No file selected.
            </span>
          </label>
        </div>
      </div>
      <% if !@workout.video_clip.present? %>
        <%#= image_tag @workout.video_clip.preview(resize: "400x400") %>
      <% else %>
        <%= video_tag url_for(@workout.video_clip), controls: '' %>
      <% end %>
      <br />
      <div class="actions">
        <%= form.submit 'Upload', :class => 'button is-dark is-radiusless is-fullwidth' %>
      </div>
    </div>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

<h1>Edit Workout</h1>

<%= render 'form', workout: @workout %>

app/views/workouts/index.html.erb
<% if notice %>
  <div class="notification is-info">
    <button class="delete"></button>
    <%= notice %>
  </div>
<% end %>

<h1 class="title">All Workouts</h1>

<%= link_to 'New Workout', new_workout_path, class: "is-pulled-right" %>

<%= form_tag(workouts_path, method: :get) do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search ...", class: "input is-dark is-radiusless" %>
  <%= submit_tag "", name: nil, style: "display: none;" %>
<% end %>

<table class="table is-fullwidth">
  <thead>
    <tr>
      <th class="is-3">Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td class="is-capitalized" style="width: 20em;"><strong><%= workout.title %></strong></td>
        <td><%= sanitize workout.description.to_s.truncate(300, separator: /\s/) %></td>
        <td><%= link_to 'Show', workout %></td>
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%== pagy_bulma_nav(@paginated_results) %>

app/views/workouts/new.html.erb
<%= link_to 'Back', workouts_path %>

<h2 class="title">New Workout</h2>

<%= render 'form', workout: @workout %>

app/views/workouts/show.html.erb
<% if notice %>
  <div class="notification is-info">
    <button class="delete"></button>
    <%= notice %>
  </div>
<% end %>

<%= link_to 'Back', workouts_path %>

<div class="columns">
  <div class="column is-half">
    <%= video_tag(url_for(@workout.video_clip), controls: '') %>
  </div>
  <div class="column is-half">
    <h1 class="title"><%= @workout.title %></h1> <%= link_to 'Edit', edit_workout_path(@workout) %>
    <p class="content"><%= @workout.description %></p>
  </div>
</div>